version: '3'
networks:
    app-network: null
services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
            - './src:/var/www/html'
        ports:
            - 81:80
        restart: always
        depends_on:
            - php
            - postgres
        networks:
            - app-network
    php:
        build: php
        restart: always
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            #- ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./src:/var/www/html
        networks:
            - app-network
    composer:
        image: composer
        volumes:
            - './src:/var/www/html'
        command: install
        working_dir: /var/www/html
        networks:
            - app-network
    npm:
        image: 'node:13.7'
        container_name: 'npm'
        volumes:
            - './src:/var/www/html'
        working_dir: /var/www/html
        entrypoint:
            - npm
    postgres:
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5438:5432
        volumes:
            - ./database/:/docker-entrypoint-initdb.d/
        networks:
            - app-network
        
